// Test sur Try...catch pour mes cheat sheets

// Exemple de try... catch qui fonctionne

try{
    console.log(Math.random(1,10))
}catch(err){
    console.log("Math.random is not working")
}